### ISSUE TITLE
Returns 0,0 for tests

### ISSUE THREAD

**Issue by TheZoraiz** [nathan-fiscaletti/consolesize-go#3]
It works completely fine when executed with `go run main.go`, even if the consolesize-go is imported down in other imported libraries from `main.go`. Even the binaries work fine.

However, it doesn't seem to do that for go tests. I wrote a simple test in a `library_test.go` file to show this:

```go
package main

import (
	"fmt"
	"testing"

	"github.com/nathan-fiscaletti/consolesize-go"
)

func TestLibrary(t *testing.T) {
	cols, rows := consolesize.GetConsoleSize()
	fmt.Printf("Rows: %v\n", rows)
	fmt.Printf("Cols: %v\n\n", cols)

	t.FailNow()
}
```

<br>

When I execute `go test library_test.go`, I get the following output:

<p  align="center">
<img width="650" src="https://user-images.githubusercontent.com/53083869/120307852-e1206880-c2ec-11eb-90a0-a539a47e123d.png">
</p>

<br>

I've separated a chunk of my cli tool to be used as a library, but I can't write any tests for it due to this issue. Any idea how I could resolve this?

**Comment by nathan-fiscaletti** [comment]
I'm only speculating, but I believe this is due to the way in which `go test` takes over stdout. Can you attempt to run the same `go test` invocation with `-v`?

**Comment by TheZoraiz** [comment]
@nathan-fiscaletti Got mostly the same output with `go test library_test.go -v`

<p align="center">
  <img width=600 src="https://user-images.githubusercontent.com/53083869/120549991-bb3eb500-c40d-11eb-93a1-6b8c784e2405.png" >
</>

<br>

I think you're right about Go tests behaving differently than expected with stdout. Is it possible that this issue is somewhere in the built-in libraries? `consolesize_unix.go` only has one function call so I doubt it's an issue with the library now.

I copy pasted the unix code directly into the `library_test.go` like so:
```go
package main

import (
	"fmt"
	"syscall"
	"testing"
	"unsafe"
)

func TestLibrary(t *testing.T) {

	var sz struct {
		rows    uint16
		cols    uint16
		xpixels uint16
		ypixels uint16
	}
	_, _, _ = syscall.Syscall(syscall.SYS_IOCTL,
		uintptr(syscall.Stdout), uintptr(syscall.TIOCGWINSZ), uintptr(unsafe.Pointer(&sz)))

	fmt.Println("Value of sz: ", sz)
	t.FailNow()
}
```

<br>
And got this:

<p align="center">
  <img width=600 src="https://user-images.githubusercontent.com/53083869/120551854-f215ca80-c40f-11eb-8bdd-afb091ce0544.png" >
</>

**Comment by nathan-fiscaletti** [comment]
The way this works on unix operating systems is it uses the [`TIOCGWINSZ` ioctl command](http://www.delorie.com/djgpp/doc/libc/libc_495.html) with the `stdout` file descriptor. The `go test` command overrides `stdout` (I believe, I'm not 100% positive on this). 

You might also try replacing `uintptr(syscall.Stdout)` with `uintptr(syscall.Stderr)` in `consolesize_unix.go` and see if it has any effect. Still, no guarantees it will fix anything. 

I need to find some time to sit down and attempt to replicate this behavior locally.

**Comment by nathan-fiscaletti** [comment]
@TheZoraiz did changing it to `syscall.Stderr` fix the issue with `go test`?

**Comment by TheZoraiz** [comment]
@nathan-fiscaletti I'm afraid not. Sorry if the thumbs up was misleading. I tried with `syscall.Stderr`, `os.Stdout.Fd()` and `os.Stderr.Fd()` as well but got the same result.

Thinking of implementing tests manually now. That seems to be the only solution so far :/

**Comment by nathan-fiscaletti** [comment]
@TheZoraiz A common solution for situations in which you might need the console-size to complete a test case, you can instead mock the function and return some hard coded values to run the tests with. It's common for data that's variable like this to simply be mocked for the purposes of tests.

**Comment by rbrt-weiler** [comment]
`go test` seems to be a headless environment, i.e. one that does not provide a console. So `(0, 0)` is basically the valid return value, because a non-existing console has 0 rows and 0 cols.
